CREATE TABLE IF NOT EXISTS "user" (
    "id"            INTEGER     NOT NULL
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid"          BIGINT      NOT NULL
        UNIQUE
);

CREATE TABLE IF NOT EXISTS "user_game_session" (
    "user_id"       INTEGER     NOT NULL
        REFERENCES "user" (id) ON DELETE CASCADE,
    "server_id"     VARCHAR(64) NOT NULL,
    "name"          VARCHAR(64) NOT NULL,
    "address"       INET        NOT NULL,
    "started_at"    TIMESTAMP   NOT NULL,
    "ended_at"      TIMESTAMP   NOT NULL
);
