name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set Release Version
        run: |
          ./gradlew incrementVersionFile
          echo "RELEASE_VERSION=$(cat VERSION.txt)" >> $GITHUB_ENV

      - name: Build Artifact
        run: ./gradlew build
        env:
          ORG_GRADLE_PROJECT_releaseVersion: "${{ env.RELEASE_VERSION }}"

      - name: Build and Publish Artifacts
        run: ./gradlew build publish
        env:
          ORG_GRADLE_PROJECT_xpdustryUsername: "${{ secrets.XPDUSTRY_MAVEN_USERNAME }}"
          ORG_GRADLE_PROJECT_xpdustryPassword: "${{ secrets.XPDUSTRY_MAVEN_PASSWORD }}"
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.XPDUSTRY_MAVEN_SIGNING_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.XPDUSTRY_MAVEN_SIGNING_PASSWORD }}"
          ORG_GRADLE_PROJECT_releaseVersion: "${{ env.RELEASE_VERSION }}"

      - name: Set up Artifacts Upload
        run: |
          echo "MINDUSTRY_ARTIFACT_PATH=$(./gradlew :nucleus-mindustry:getArtifactPath -q)" >> $GITHUB_ENV
          echo "DISCORD_ARTIFACT_PATH=$(./gradlew :nucleus-discord:getArtifactPath -q)" >> $GITHUB_ENV

      - name: Upload Artifacts to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.MINDUSTRY_ARTIFACT_PATH }}
            ${{ env.DISCORD_ARTIFACT_PATH }}

      - name: Commit Updated Version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: Increment version
          file_pattern: VERSION.txt
